using System.Diagnostics;
using AirClipCCL.ViewModels;
using AirClipCCL.Views;
using Avalonia.Controls;
using CommunityToolkit.Mvvm.ComponentModel;

namespace AirClipApp.Views;

/// <summary>
/// The main window of our application, which should be the only window. 
/// </summary>
/// <resources> Mostly auto-generated by Avalonia. </resources>
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        
        /*
        var row = ActivePage.FindControl<ScrollableSelectionRow>("SelectionRow");
        var rowDataContext = row?.DataContext;
        if (rowDataContext is not ScrollableSelectionRowViewModel rowViewModel)
            return;
        */
    }

    
}