using Avalonia.Controls;

namespace AirClipApp.Views;

/// <summary>
/// The main window of our application, which should be the only window. 
/// </summary>
/// <resources> Mostly auto-generated by Avalonia. </resources>
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        PageContent.Content = new HomePage(); // Show Home page when the app starts
    }

    
}