using System;
using Avalonia.Controls;
using Avalonia.Controls.Templates;
using AirClipApp.ViewModels;
using CommunityToolkit.Mvvm.ComponentModel;

namespace AirClipApp;

/// <summary>
/// Helps locate Views from ViewModels. Frankly I'm not sure why this is necessary.
/// </summary>
/// <resources> Auto-generated by Avalonia. </resources>
public class ViewLocator : IDataTemplate
{
    public Control? Build(object? param)
    {
        if (param is null)
            return null;

        var name = param.GetType().FullName!.Replace("ViewModel", "", StringComparison.Ordinal);
        var type = Type.GetType(name);

        if (type != null)
        {
            return (Control)Activator.CreateInstance(type)!;
        }

        return new TextBlock { Text = "Not Found: " + name };
    }

    public bool Match(object? data)
    {
        return data is ObservableObject;
    }
}